### ISSUE TITLE
Receiving messages when app is in background

### ISSUE THREAD

**Issue by j-rewerts** [livechat/chat-window-ios#10]
I'm currently trying to allow notifications in my iOS app. If a visitor is using the app and closes it, I'd like them to receive notifications when an agent responds to them at least for a short while after closing the app.

**Comment by j-rewerts** [comment]
In order to test an easy implementation of this, I've added UIApplication.shared.beginBackgroundTask to the class that implements LiveChatDelegate. The code in my delegate continues to run when the app is closed, but I no longer receive any messages.

**Comment by j-rewerts** [comment]
I've confirmed this on an iPhone 5, iOS version 10.3.3.

**Comment by Jercik** [comment]
Hi, unfortunately it is not possible to receive messages while app is in background. This chat widget works by running JavaScript code in hidden WKWebView, and WKWebView just stop executing any code when app enters background.
