### ISSUE TITLE
How to handle LiveChat errors

### ISSUE THREAD

**Issue by j-rewerts** [livechat/chat-window-ios#11]
I've been running into an error NSURLErrorDomain -999 every now and then. It's a fairly harmless error as far as I'm aware, but LiveChat displays the error. I found this by looking in ChatView.swift lines 413-415:

```swift
if error.domain == NSURLErrorDomain && error.code == -999 {
    loadingView.displayLoadingError(withMessage: error.localizedDescription)
}
```

Ideally, I'd like to be able to handle this error myself, or just have it swallowed. I can modify the LiveChat source in my pods is another option I suppose. 

From what I've read, the error simply means a request was cancelled, not that the request failed or anything.

**Comment by Jercik** [comment]
Hi, I've made changes in version `2.0.10` and alert will no longer be shown to users for `-999` errors.
