### ISSUE TITLE
Disale 3D Touch 

### ISSUE THREAD

**Issue by bombez** [livechat/chat-window-ios#12]
Hi,
I would like to know if there is a possibility to disable the 3D Touch functionality.
To be more clear I've attach a video.

Thanks
[issue-24.mov.zip](https://github.com/livechat/chat-window-ios/files/1618942/issue-24.mov.zip)

**Comment by Jercik** [comment]
Hi, the issue is fixed in version `2.0.10`. Please update your dependency.
