### ISSUE TITLE
Status Bar error

### ISSUE THREAD

**Issue by bombez** [livechat/chat-window-ios#13]
Hi,
in my app I've notice that there's a problem with the status bar, 
![issue](https://user-images.githubusercontent.com/14980441/34936908-402bd5ac-f9e3-11e7-9e4b-71634e4c9bec.jpg)
that iOS behavior is only present on the os version previous than the 11.
Could you please investigate?
Thanks

**Comment by Jercik** [comment]
Hi, I've fixed issue on iOS 10 and earlier in widget version `2.0.10`. Please update your dependency.
