### ISSUE TITLE
Strange Behavior

### ISSUE THREAD

**Issue by bombez** [livechat/chat-window-ios#15]
Hi,
I notice this strange behavior during the test, could you please review?
Thanks
[Issue.mp4.zip](https://github.com/livechat/chat-window-ios/files/1716548/Issue.mp4.zip)

**Comment by bombez** [comment]
@Jercik could you please help me on this?
Thanks

**Comment by kamil-szostakowski** [comment]
@bombez is this still an issue?

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
