### ISSUE TITLE
Pre-chat survey not filled automatically

### ISSUE THREAD

**Issue by jaysson** [livechat/chat-window-ios#16]
I am creating an app with login flow. Since I know the email & name of the person, I would like to skip pre chat survey and use those details instead. However, programmatically setting name and email isn't working.

I tried the same with a very basic single view controller xcode project. Outlets and action are properly connected. I am getting the name and email printed in console. However, pre chat survey still appears in chat window.

```swift
// ViewController.swift

import UIKit
import LiveChat

class ViewController: UIViewController {

    @IBOutlet var nameField: UITextField!
    @IBOutlet var emailField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        LiveChat.licenseId = "My license id"

        // Do any additional setup after loading the view, typically from a nib.
    }

    @IBAction func startChat(_ sender: Any) {
        LiveChat.clearSession() // Tried with and without
        LiveChat.name = nameField.text!
        LiveChat.email = emailField.text!
        print(emailField.text!)
        print(nameField.text!)
        LiveChat.presentChat()
    }
}
```

**Comment by kamil-szostakowski** [comment]
@jaysson are you still experiencing that issue?

**Comment by jaysson** [comment]
I am not using Livechat anymore.

**Comment by kamil-szostakowski** [comment]
Closing as not reproducible.
