### ISSUE TITLE
Chat window keep loading on device , IOS APP

### ISSUE THREAD

**Issue by loaielayan** [livechat/chat-window-ios#18]
Hi , Implemented chat to my IOS App , it works fine on simulator but the chat window keep loading on actual IOS device

thanks

**Comment by nick-iCars** [comment]
I'm having this issue too. I used your example app to test, and it works fine with the LiveChat company ID included in the repo, but when I put our company ID in it shows the loading spin screen indefinitely. Same behavior as when implemented in our own app's code. Any suggestions?

**Comment by nick-iCars** [comment]
Can someone get in touch with me, the support center is no help. Is there anything I need to enable on our account for this to work? Seems odd that your sample app doesn't work with our key.

**Comment by nick-iCars** [comment]
I replaced channel name with "0" works now

**Comment by kamil-szostakowski** [comment]
@nick-iCars  looks like this is a duplicate of #25. Please let me know if you are still experiencing this issue.
