### ISSUE TITLE
Chat window drawing issues on iPhone with iOS 12.2

### ISSUE THREAD

**Issue by alrosello** [livechat/chat-window-ios#32]
We have an issue with using the Chat Widget on the iPhone with iOS 12.2, 12.1 , 12.0, 11.2.6

**Steps To Reproduce**
1. Open iOS app with widget integrated on an iPhone with iOS 12.2
2. Start Live Chat 
3. Fill out prechat survey
4. Agent Starts the chat which triggers the chat thread to open in the app

Basically the message entry text box and send button end up in the middle of the screen detached from the top of the keyboard.  The header part of the chat thread is pushed up off the top part of the screen.  We have to scroll up and down to enter a message and see the thread since the top of the thread and the message entry area do not show in the window together.  Also i can scroll down forever.   

Another issue is that the chat thread itself only shows like 2 or 3 lines of the chat thread which makes it difficult to read of course.  

Also this only happens when we first open the app.  After I shut the thread and start a new one then the window behaves better but not perfect.  We do not have the scrolling down forever issue but it still requires the user to scroll up and down to enter the text and see the thread.   The iPhone X also seems to exhibit this behavior.   

Here is an image showing the various screenshot issues with an explanation once the chat thread is started:  
![Chat Issue on iPhone XS Max](https://user-images.githubusercontent.com/22150967/55921811-5c35da80-5bcc-11e9-9102-c6b17d61911a.png)

You can also access a video of this issue here 
https://1drv.ms/v/s!AoGc1ryuVd50fMx_I8eXZ9OuONk

Any help asap would be greatly appreciated.  Thanks for the great work!!

**Comment by kamil-szostakowski** [comment]
Thanks for the great video explanation. I will check that soon.

**Comment by alrosello** [comment]
We are using 2.0.13

**Comment by alrosello** [comment]
So LiveChat support suggested that we switch to the latest live chat update since we were using the older version still.  So we switched to the new version and we are having a much better experience with iOS 12.2.  The Chat window header still scrolls up off the screen, but the chat thread is still visible on the screen and does not require the user to scroll up and down to chat.   Here is an updated video showing the results. 

https://1drv.ms/v/s!AoGc1ryuVd50fTxMo9tLn1tKAk0

**Comment by kamil-szostakowski** [comment]
@alrosello We investigated that problem on both platforms and this behavior turned out to be caused by a differences in implementations of web view on Android and iOS. When keyboard pops up, Android resizes the visible content area so the chat view gets resized as well. In the same situation, iOS leaves the visible content area unchanged so it gets scrolled up and top bar gets hidden.

Unfortunately, there is nothing we can do about that. These are platform specific details.

**Comment by alrosello** [comment]
Ok thanks for the review and response.  I think based on what we saw last week after changing to the latest chat widget theme that the functionality works well enough and will not impact the user experience.
