### ISSUE TITLE
Chatting bug appearing twice when pressed once!

### ISSUE THREAD

**Issue by dbalk001** [livechat/chat-window-ios#34]
I've downloaded the latest version and having this issue.

https://thinkbusinessfinance-my.sharepoint.com/:v:/g/personal/david_balkwill_thinkbusinessloans_com/Ee35Qh0WXGtEnMbYgu40FuYB8Qm4kzHxYKdXsbCoXg2iCw?e=URXBlr

Thanks

**Comment by kamil-szostakowski** [comment]
Fixed in version 2.0.15
