### ISSUE TITLE
swift build error 

### ISSUE THREAD

**Issue by Zhipeng-Chang** [livechat/chat-window-ios#35]
Hi, 
I'm running into a build error:

the error message is: 
"Value of type 'CustomVariables' (aka 'Array<(String, String)>') has no member 'firstIndex'"

from this line of code:
https://github.com/livechat/chat-window-ios/blob/70c846185998d574a7c95b67e68ea77cb1a6fd1f/Sources/LiveChat.swift#L132

**Comment by kamil-szostakowski** [comment]
What are the Xcode and Swift versions you are using in your project?

**Comment by Zhipeng-Chang** [comment]
Hi @kamil-szostakowski ! Thank you for getting back! I have found the reason for that, I was using Swift 4.0, for some reasons, it doesn't support function "firstIndex", after I changed to "index", it works!
