### ISSUE TITLE
Status bar style

### ISSUE THREAD

**Issue by bull-xu** [livechat/chat-window-ios#38]
The lib should have the ability (configuration) to set the status bar style. The `UIViewControllerBasedStatusBarAppearance ` in info.plist sets to YES in our project, the status bar style we want to show is `.lightContent` when the Live Chat window is open. It seems the status bar style is `.default` by default.

**Comment by kamil-szostakowski** [comment]
Fixed in #42. Will be available in version 2.0.16.

**Comment by kamil-szostakowski** [comment]
Released in 2.0.16.

**Comment by bull-xu** [comment]
Hi @kamil-szostakowski could you please advise that where can I set the status bar style for the `LiveChatOverlayViewController`? Thanks.

**Comment by kamil-szostakowski** [comment]
Hi @bull-xu, sorry for late response. After discussion with product team we decided to fill entire screen with with the widget. It means that the background under the status bar will be white and and the status bar style for the widget remains .default so the visual aspects of the widget and hosting app won't overlap.

**Comment by bull-xu** [comment]
Hi @kamil-szostakowski thanks for your response. I'm happy the latest changes on filling the entire screen with the widget. It looks better.
