### ISSUE TITLE
Not able to clearSession()

### ISSUE THREAD

**Issue by anandcapgemini** [livechat/chat-window-ios#39]
When i call clearSession() it works well as expected. But when i again launch my bot after clearing out sesssion, the delegate method for livechat did not get  called. 'received' method stops calling immediately after calling clear sesssion.

**Comment by anandcapgemini** [comment]
any update on the issue

**Comment by kamil-szostakowski** [comment]
Could you please provide more detail on that issue? All the steps required for reproduction. Sample project illustrating the problem would be ideal.

**Comment by kamil-szostakowski** [comment]
Closed due to the inactivity.
