### ISSUE TITLE
iOS 9 Compatibility

### ISSUE THREAD

**Issue by simonlinj** [livechat/chat-window-ios#4]
Hi
Any specific reason you are dropping iOS 9 compatibility? 

01939c7a12e10222c3a44d5602a3a129151dc6cb
As far as I know, Swift 4 is still compatible with iOS 7 and above. Please re-add iOS 9 support in the next release if posible. Thank you very much!

**Comment by simonlinj** [comment]
#5

**Comment by ZiggyKraus** [comment]
Hello @simonlinj ,

Thank you for reaching us with this case! I'm happy to report that we have [re-established](https://github.com/livechat/chat-window-ios/commit/7c1d87ab1c3eb7777fce771c217ca8a7090df93d) the support of iOS 9 in our LiveChat iOS widget – we apologize for the inconvenience! 

In case of any additional questions, please don't hesitate to ask.
