### ISSUE TITLE
Support for iPhoneX, XR, Xs and MAX

### ISSUE THREAD

**Issue by prashantdabhi9033** [livechat/chat-window-ios#40]
the presented view controller is not compatible with iphoneX, XS, MAX and XR 

please add safe area layout and display over the full view 

currently when present chat view we can see the view controller which is behind the chat view 

also make the dismiss chat view delegate override so if user dismiss the chat we can handle that as per our reuirements
![IMG_0003](https://user-images.githubusercontent.com/16433965/59335221-c62c4680-8d19-11e9-8cb8-78aaadfd75c9.PNG)

**Comment by kamil-szostakowski** [comment]
Fixed in #42. Will be available in version 2.0.16.

**Comment by kamil-szostakowski** [comment]
Released in 2.0.16
