### ISSUE TITLE
Pod file issue in iOS App installation

### ISSUE THREAD

**Issue by Hamza123Imran** [livechat/chat-window-ios#46]
Hi, my Xcode version is 11.0 and i'm trying to install LiveChat through pod file with name,
`pod 'LiveChat', '~> 2.0.17'` . Now when i install the file through terminal it shows me this error,
`CocoaPods could not find compatible versions for pod "LiveChat":
In Podfile:
LiveChat (~> 2.0.17)`. How can i resolve this issue? What is the new pod file?

**Comment by kamil-szostakowski** [comment]
Hi @Hamza123Imran I'm not able to reproduce the issue on my side on Xcode 11 (official, installed from AppStore). What is the version of iOS you are targeting for?

**Comment by Hamza123Imran** [comment]
I'm running my app on simulator and my minimum version is 10.0,
My xcode version is 11.0
This is pod file i'm trying to install. pod 'LiveChat', '~> 2.0.17' . @kamil-szostakowski

**Comment by kamil-szostakowski** [comment]
@Hamza123Imran could you please share your entire Podfile?

**Comment by Hamza123Imran** [comment]
[Podfile.zip](https://github.com/livechat/chat-window-ios/files/3653676/Podfile.zip)
This is my pod file

**Comment by kamil-szostakowski** [comment]
@Hamza123Imran I tried with your podfile and everything was installed just fine. Do you use swift, if yes which version? Are you sure that you are not targeting tvOS or any other platform?
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing Alamofire (4.8.2)
Installing AppAuth (1.2.0)
Installing CardsLayout (0.0.1)
Installing CountryPickerView (3.0.3)
Installing FBSDKCoreKit (5.5.0)
Installing FBSDKLoginKit (5.5.0)
Installing FBSDKShareKit (5.5.0)
Installing FacebookCore (0.8.0)
Installing FacebookLogin (0.8.0)
Installing FacebookShare (0.8.0)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleMaps (3.1.0)
Installing GooglePlacePicker (3.1.0)
Installing GooglePlaces (3.1.0)
Installing GoogleSignIn (5.0.0)
Installing IQKeyboardManagerSwift (6.4.1)
Installing ListPlaceholder (1.4)
Installing LiveChat (2.0.17)
Installing MRCountryPicker (0.0.8)
Installing NVActivityIndicatorView (4.7.0)
Installing SDWebImage (4.4.7)
Installing SkeletonView (1.8.1)
Installing SkyFloatingLabelTextField (3.7.0)
Installing SwiftyJSON (4.3.0)
Installing TTRangeSlider (1.0.6)
Installing XLPagerTabStrip (8.1.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 21 dependencies from the Podfile and 27 total pods installed.

[!] Automatically assigning platform `ios` with version `11.0` on target `LCWidget-Pods` because no platform was specified. Please specify a platform for this target in your Podfile. See https://guides.cocoapods.org/syntax/podfile.html#platform.
```

**Comment by Hamza123Imran** [comment]
No application is only for iPhone and my language version is Swift 4.2 . @kamil-szostakowski

**Comment by kamil-szostakowski** [comment]
@Hamza123Imran could you please try `pod repo update` and then `pod install`?

**Comment by Hamza123Imran** [comment]
okay let me try. @kamil-szostakowski

**Comment by Hamza123Imran** [comment]
Yeah Now working fine, thanks for your help : ) . @kamil-szostakowski
