### ISSUE TITLE
Support different status bar color via delegation

### ISSUE THREAD

**Issue by andymedvedev** [livechat/chat-window-ios#47]
Support variable `preferredStatusBarStyle` via delegation in `LiveChatOverlayViewController`.

example code: 
```
override var preferredStatusBarStyle: UIStatusBarStyle {
    return delegate?.preferredStatusBarStyle() ?? .default
}
```

**Comment by andymedvedev** [comment]
viewController is fixed. no more needing to configure status bar

**Comment by Hamza123Imran** [comment]
@andymedvedev brother which pod file r u using in ur app?

**Comment by kamil-szostakowski** [comment]
@andymedvedev @Hamza123Imran status bar on the chat widget screen is always white per design, there is no way to customize.
