### ISSUE TITLE
How to show default chat widget in iOS App. 

### ISSUE THREAD

**Issue by varindersingh670** [livechat/chat-window-ios#49]
I have followed below process to setup chat widget for iOS Mobile. but chat widget is not displaying on App.
**Go to Settings → Chat Window → Customization and click on Mobile Chat widget.** 

 is there any code for showing / hiding chat widget permanently?
I am stuck on this point. if anyone have idea about ,please let me know.
Thanks

**Comment by Hamza123Imran** [comment]
@varindersingh670  through which pod file u r integrating in iOS app?

**Comment by kamil-szostakowski** [comment]
@varindersingh670 have you tried samples from the README?

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
