### ISSUE TITLE
While adding the framework to app facing the issue that "no such module LiveChat"

### ISSUE THREAD

**Issue by SaiPrasadNavtech** [livechat/chat-window-ios#53]
I tried with cocoa pods and manually added them. In my app, I am using Objective-c and Swift language and I am trying to import the framework in Appdelegate.m file and I am using Xcode 11.3

**Comment by PPLLock** [comment]
Hello, I also get an error when running the demo here: CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'LiveChat' from project 'Pods')
     cd / Users / apple / Downloads / chat-window-ios-master / Examples / Example-ObjC / Pods
     export DEVELOPER_DIR = / Applications / Xcode.app / Contents / Developer
     export SDKROOT = / Applications / Xcode.app / Contents / Developer / Platforms / iPhoneOS.platform / Developer / SDKs / iPhoneOS13.2.sdk
     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name LiveChat -Onone -enable-batch-mode -enforce-exclusivity = checked @ / Users / apple / Library / Developer / Xcode / DerivedData / Example-ObjC-dtwupsaocsjqpyafpfelzwkyuher

**Comment by PPLLock** [comment]
Hello, I also get an error when running the demo here: CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'LiveChat' from project 'Pods')
     cd / Users / apple / Downloads / chat-window-ios-master / Examples / Example-ObjC / Pods
     export DEVELOPER_DIR = / Applications / Xcode.app / Contents / Developer
     export SDKROOT = / Applications / Xcode.app / Contents / Developer / Platforms / iPhoneOS.platform / Developer / SDKs / iPhoneOS13.2.sdk
     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name LiveChat -Onone -enable-batch-mode -enforce-exclusivity = checked @ / Users / apple / Library / Developer / Xcode / DerivedData / Example-ObjC-dtwupsaocsjqpyafpfelzwkyuher

**Comment by kamil-szostakowski** [comment]
@SaiPrasadNavtech , @PPLLock do you guys still experience this issue? Both sample apps works fine. What is your setup? Xcode version, iOS version, Swift/Objc, Swift version?

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.

**Comment by nickkhodcts** [comment]
Also experiencing this issue. Xcode 14, MacOS 12.6.

Installed LiveChat via CocoaPods. Project on Swift. 
Getting No such module 'LiveChat' when adding import LiveChat
