### ISSUE TITLE
Would like to have some kind of callback to know whether the chat has ended or is ongoing after being minimized

### ISSUE THREAD

**Issue by smckenzieSP** [livechat/chat-window-ios#54]
I'm wanting to have a chat bubble visible on all screens when an active chat is going, it would be nice to have some way to know when the chat has ended so the chat bubble can be removed.

**Comment by studentIvan** [comment]
+1 why we have this in the javascript API but not in the swift?

**Comment by kamil-szostakowski** [comment]
@smckenzieSP @studentIvan unfortunately this feature is not planned to be included in the widget for a time being.
