### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by jelenadj** [livechat/chat-window-ios#57]
Is it planned to migrate to Swift 5 anytime soon?
I've noticed there's already an open PR for that: https://github.com/livechat/chat-window-ios/pull/44

**Comment by jelenadj** [comment]
There's another PR for this as well, any chance we can get it handled sometimes soon? https://github.com/livechat/chat-window-ios/pull/61

**Comment by denis-hoz** [comment]
bump

**Comment by kamil-szostakowski** [comment]
Implemented in version `2.0.19`.
