### ISSUE TITLE
White screen when trying to open chat if internet connection is lost after initializing app

### ISSUE THREAD

**Issue by smckenzieSP** [livechat/chat-window-ios#58]
There's no back/refresh/close options, it forces the user to kill the app

**Comment by kamil-szostakowski** [comment]
@smckenzieSP Is this still reproducible? I can see a close button in the top right corner?

![Simulator Screen Shot - iPhone SE - 2020-07-21 at 09 51 44](https://user-images.githubusercontent.com/9430934/88027859-281fc800-cb38-11ea-869a-a03a7d090725.png)

**Comment by smckenzieSP** [comment]
Hey, I'm seeing the same as you. The reload button doesn't seem to work for me though, the spinner just endlessly cycles. The user can exit out now so that's a lot better.

**Comment by kamil-szostakowski** [comment]
Ok it looks like the problem is resolved then. The spinner issue might be cause by the connectivity issue as a widget tries to reconnect to the server.
