### ISSUE TITLE
Not opening livechat

### ISSUE THREAD

**Issue by bidawat** [livechat/chat-window-ios#59]
I am trying to integrate LiveChat in IOS app but getting below error message.

WebViewBridge unknown messageType: {
    messageType = uiReady;
}

#this is my code
let sm = SessionManager()
        let LIVECHAT_SUPPORT_LICENCE_NR = "licencekey"
        LiveChat.licenseId = LIVECHAT_SUPPORT_LICENCE_NR
        LiveChat.groupId = "0"
        LiveChat.name = "\(sm.firstName) \(sm.lastName)"
        LiveChat.email = sm.email
        LiveChat.setVariable(withKey:"mobile", value:sm.mobile ?? "")
        
        LiveChat.presentChat()

**Comment by kamil-szostakowski** [comment]
This is actually not an error but a message saying that the widget received unsupported message from the service. Nothing critical. Is there any other problem we can assist you with?

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
