### ISSUE TITLE
EditText disappears  when Keyboard popup

### ISSUE THREAD

**Issue by simonlinj** [livechat/chat-window-ios#6]
The EditText is not visible when typing.  Tested on iPhone 7 iOS 11.1.1 

![whatsapp-video-2017-11-13-at-10 19 41-am](https://user-images.githubusercontent.com/1506890/32728415-060b2b4e-c85f-11e7-9658-172dbae7bdaa.gif)

**Comment by ZiggyKraus** [comment]
Hello @simonlinj !

Would it be possible for you to provide us with a working app where we could investigate this behaviour? If that's the case, we will truly appreciate it!

Thank you very much in advance. Also, in case of any additional questions, please don't hesitate to as.

**Comment by Jercik** [comment]
Fixed in `2.0.7`

**Comment by rafiq34** [comment]
How can active my id please help me

**Comment by msypko** [comment]
Hi @rafiq34!

This issue is now closed - I recommend you to visit our chat on www.livechatinc.com and elaborate your question. Our Support Heroes would be happy to help you :-) Our operators are available 24/7/365.

You can always shoot us an email too: support@livechatinc.com
