### ISSUE TITLE
⚠️ UIWindowScene warning message

### ISSUE THREAD

**Issue by abdulla-allaith** [livechat/chat-window-ios#64]
There's a constant warning showing in Xcode:
WARNING: `'UIWindowScene' is only available on iOS 13.0 or newer.`
in `LiveChat-Swift.h` file
in 2 functions:
`+ (UIWindowScene * _Nullable)windowScene SWIFT_WARN_UNUSED_RESULT;`
`+ (void)setWindowScene:(UIWindowScene * _Nullable)value;`

Possibly might be fixed by surrounding the block of code with `@available 13.0` check, and use alternative code for devices with iOS < 13.0

**Comment by kamil-szostakowski** [comment]
@abdulla-allaith thanks for pointing this out. All the usages of `UIWindowScene` in the widget are annotated with @available. It looks like Xcode also generates setter and getter for this static property which doesn't inherit this annotation and it causes a warning. We will try to address this issue in the next planned release.

**Comment by kamil-szostakowski** [comment]
Hello @abdulla-allaith widget got bumped up to iOS 15 in version `2.0.25` this warning should be gone now.
