### ISSUE TITLE
message sent to deallocated instance 0x13dd6f510

### ISSUE THREAD

**Issue by shemingkai** [livechat/chat-window-ios#69]
I used object-C to integrate with LiveChat's SDK, and I downloaded the Demo(chat-window-ios) from Github.
But when I ran Example-objc in Xcode, it gave me an error.
The Xcode version I used is 11.6, the test device is an apple 6s, and the system version is IOS9.3.2.
The error is [_TtC8LiveChatP33_1F81995BCB419BD11C66D51FB47778B022ActivityIndicatorLayer release]: message sent to deallocated instance 0x13dd6f510

**Comment by kamil-szostakowski** [comment]
@shemingkai unfortunately, iOS 9 is no longer supported by our team. Currently (v2.0.21) we support iOS 11+.
