### ISSUE TITLE
Livechat page fails to load

### ISSUE THREAD

**Issue by VinayRajK95** [livechat/chat-window-ios#73]
Livechat screen displays blank screen and there is no way to dismiss the blank screen therefore user has to restart the app .

For sdk to render the chat screen, a script message should be received from the webpage (messageType : uiReady). Which is not been received when using our license id and is working fine for the example license id(1520).

attached screenshot for reference. 
Could you please look into this issue?

email: vinay.kanthraj@sgdigital.com

![Livechat_blank_screen](https://user-images.githubusercontent.com/59496990/97956923-de4dab80-1dcf-11eb-8269-667d05afd181.png)

**Comment by VinayRajK95** [comment]
Hi LiveChat Team,

This issue is not app specific. I'm unsure if there is issue either with license id validation or sdk.

Blank screen is also seen in the sample app provided, when we plugin customer license id there.

As previously mentioned, I have noticed a discrepancy, a message from webView is not been received when using customer license id.

WebViewBridge unknown messageType: {
    messageType = uiReady;
}

Could you please prioritise this issue and investigate from the sdk perspective as what could be the cause for it?

Thanks

**Comment by kamil-szostakowski** [comment]
@VinayRajK95 thanks for your report. Could you please provide a licenseId you are using so we will be able to investigate the issue?

**Comment by VinayRajK95** [comment]
Hi @kamil-szostakowski ,

Its loading now. thanks
