### ISSUE TITLE
LiveChat Header is not properly visible

### ISSUE THREAD

**Issue by VinayRajK95** [livechat/chat-window-ios#74]
Livechat Header is not readable due to low contrast between label and the view.
![GN_NJ - iOS - Live Chat](https://user-images.githubusercontent.com/59496990/103739103-203ade00-501b-11eb-96d2-b3cbc7fa3f55.png)

attached screenshot for reference.
Could you please look into this issue?

email: vinay.kanthraj@sgdigital.com

**Comment by MichalPaszowski** [comment]
Hey, that bluish colour comes from the focus that you have on this element.
To change the theme of your chat widget you can go to https://my.livechatinc.com/settings/theme pick the "More colour settings" option and choose a colour for "Title bar".

**Comment by VinayRajK95** [comment]
@MichalPaszowski thank you 😀
