### ISSUE TITLE
Chat window not opening on iOS client side, but shows in admin dashboard

### ISSUE THREAD

**Issue by djipsy6** [livechat/chat-window-ios#78]
Hi there

here is my AppDelegate Code:

`LiveChat.licenseId` = "MY LICENSE ID"
`LiveChat.delegate` = self

But whenever I call the method .presentChat, nothing appears.

No error message, nothing. Any help ?

PS: The only log I get is this:
`WebViewBridge unknown messageType: {
    messageType = uiReady;
}`

**Comment by ricky641b** [comment]
Just follow the step mentioned in the README of this repo    
     class SceneDelegate: UIResponder, UIWindowSceneDelegate {
     var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        LiveChat.windowScene = (scene as? UIWindowScene)
    }
}

**Comment by kamil-szostakowski** [comment]
Closing as already resolved.
