### ISSUE TITLE
Chat Session

### ISSUE THREAD

**Issue by bombez** [livechat/chat-window-ios#8]
Hi,
I'll currently develop an App with Login flow and I've implement the LiveChat successfully, but I've notice that there's no method to reset session.
Let me explain:
login -> start chat -> logout -> start chat

when the user start the chat for the second time, it's present the previous chat.
I think I've miss something, there's a method to reset the communication and start a new chat?? 
Thanks.

**Comment by Jercik** [comment]
Hi, I've added method called `clearSession()` which clears all cookies and website data. Please try it and tell me if it's working as expected.

**Comment by bombez** [comment]
Hi Jercik,
thank you, it is working as aspected!
