### ISSUE TITLE
IOS 14 click the link button to crash

### ISSUE THREAD

**Issue by xiadao2014** [livechat/chat-window-ios#80]
![微信图片_20210511180251](https://user-images.githubusercontent.com/6647392/117798617-e35e4c80-b283-11eb-8587-46e71195db05.png)

IOS 14 click here to crash
ios11 is ok
my plist is ok

**Comment by czartu66** [comment]
Hi, is that happening on your native app? Could you provide the screenshot from the crash? Checking this functionality on an IOS 14 and it works as designed

**Comment by xiadao2014** [comment]
![微信图片_20210511180251](https://user-images.githubusercontent.com/6647392/117972726-0eb56a00-b35e-11eb-9e42-363caee546a3.png)
It's according to the document https://developers.livechat.com/docs/getting-started/installing-livechat/ios-widget/#introduction Constructed

Inconvenient screenshot video

Click the red area button and the black screen will pop up

At present, only ios14 will be tested. Please test ios14

**Comment by xiadao2014** [comment]
Click the red button and the screen will go black

Then exit to the main interface

**Comment by kamil-szostakowski** [comment]
@xiadao2014 could you please provide us with a minimal sample project reproducing this issue? We are not able to reproduce the issue on our end, on iOS 14 as well.

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
