### ISSUE TITLE
No thread isolation

### ISSUE THREAD

**Issue by djipsy6** [livechat/chat-window-ios#89]
Hi, we just installed LiveChat SDK in our iOS App. But we have an issue: When we log in to our app using Person A, then logout and log back in with Person B, Person B can see chat transcript of Person A. Isn't there a property to set in order to identify or resume each thread. Something like LiveChat.threadId = UNIQUE_CLIENT_ID. Thanks for clarifying us.

**Comment by kamil-szostakowski** [comment]
Hi @djipsy6 I believe in this case you should call `LiveChat.clearSession()` upon logout so the next session will start from scratch. I will consult the widget team and check if switching between sessions is a supported feature.

**Comment by kamil-szostakowski** [comment]
Hi @djipsy6 I consulted the widget team and the option I shared is the only one we have at this moment. Currently we don't support switching between active threads. That request was added to the backlog so there is chance for it to be implemented in the future. Let me know if you need further assistance.
