### ISSUE TITLE
Swift package manager not supported

### ISSUE THREAD

**Issue by Anubis91** [livechat/chat-window-ios#92]
Swift package manager not supported

**Comment by lemonandlime** [comment]
...or at least its not working. There is a Package.Swift that looks like it worked sometime in the past but now it does not load into a clean project with only this dependency

**Comment by lemonandlime** [comment]
Haven't tried in a long while. If it works for you it's probably fixed

**Comment by kamil-szostakowski** [comment]
Closing as not reproducible.
