### ISSUE TITLE
Showing blank screen when run the Example of Swift

### ISSUE THREAD

**Issue by variyanirav** [livechat/chat-window-ios#95]
Hello,

I have download the latest example from GitHub and changed the licence key but when try to start live chat,

its showing the blank page to me in iOS does any facing same issue?

![Simulator Screenshot - iPhone 14 Pro - 2023-06-16 at 10 52 34](https://github.com/livechat/chat-window-ios/assets/12271615/d941b255-13d7-4d8d-a010-15e23c14c305)

**Comment by maxilapo** [comment]
+1

**Comment by kamil-szostakowski** [comment]
Yes, this is the most common source of these issues. I will add that to the docs, hope that will help someone in the future with similar problem. Thanks for the response.
